import { Domain, PreviousAssessment, GeneratedQuestionSet, MCQQuestion } from './types';

export const mockDomains: Domain[] = [
  {
    id: 'dom-1',
    name: 'JavaScript',
    topics: [
      { id: 'top-1', name: 'Variables & Data Types', availableQuestions: { easy: 15, medium: 20, hard: 10 } },
      { id: 'top-2', name: 'Functions & Closures', availableQuestions: { easy: 12, medium: 18, hard: 8 } },
      { id: 'top-3', name: 'Async/Await & Promises', availableQuestions: { easy: 8, medium: 15, hard: 12 } },
      { id: 'top-4', name: 'DOM Manipulation', availableQuestions: { easy: 10, medium: 12, hard: 6 } },
    ],
  },
  {
    id: 'dom-2',
    name: 'React',
    topics: [
      { id: 'top-5', name: 'Components & Props', availableQuestions: { easy: 18, medium: 22, hard: 10 } },
      { id: 'top-6', name: 'Hooks', availableQuestions: { easy: 15, medium: 20, hard: 15 } },
      { id: 'top-7', name: 'State Management', availableQuestions: { easy: 10, medium: 18, hard: 12 } },
      { id: 'top-8', name: 'React Router', availableQuestions: { easy: 8, medium: 10, hard: 5 } },
    ],
  },
  {
    id: 'dom-3',
    name: 'Python',
    topics: [
      { id: 'top-9', name: 'Data Structures', availableQuestions: { easy: 20, medium: 25, hard: 15 } },
      { id: 'top-10', name: 'OOP Concepts', availableQuestions: { easy: 12, medium: 18, hard: 10 } },
      { id: 'top-11', name: 'File Handling', availableQuestions: { easy: 10, medium: 12, hard: 8 } },
      { id: 'top-12', name: 'Error Handling', availableQuestions: { easy: 8, medium: 10, hard: 6 } },
    ],
  },
  {
    id: 'dom-4',
    name: 'Data Science',
    topics: [
      { id: 'top-13', name: 'Pandas & NumPy', availableQuestions: { easy: 15, medium: 20, hard: 12 } },
      { id: 'top-14', name: 'Data Visualization', availableQuestions: { easy: 12, medium: 15, hard: 8 } },
      { id: 'top-15', name: 'Machine Learning Basics', availableQuestions: { easy: 8, medium: 12, hard: 10 } },
      { id: 'top-16', name: 'Statistical Analysis', availableQuestions: { easy: 10, medium: 14, hard: 8 } },
    ],
  },
  {
    id: 'dom-5',
    name: 'Empty Domain',
    topics: [],
  },
];

export const mockPreviousAssessments: PreviousAssessment[] = [
  {
    id: 'prev-1',
    name: 'JavaScript Fundamentals Quiz',
    domains: ['JavaScript'],
    difficulty: 'Easy',
    totalQuestions: 20,
    dateTaken: '2024-01-15',
  },
  {
    id: 'prev-2',
    name: 'React Advanced Assessment',
    domains: ['React', 'JavaScript'],
    difficulty: 'Hard',
    totalQuestions: 30,
    dateTaken: '2024-01-10',
  },
  {
    id: 'prev-3',
    name: 'Full Stack Developer Test',
    domains: ['JavaScript', 'React', 'Python'],
    difficulty: 'Medium',
    totalQuestions: 50,
    dateTaken: '2024-01-05',
  },
  {
    id: 'prev-4',
    name: 'Python Basics Quiz',
    domains: ['Python'],
    difficulty: 'Easy',
    totalQuestions: 15,
    dateTaken: '2024-01-03',
  },
  {
    id: 'prev-5',
    name: 'Data Science Comprehensive',
    domains: ['Python', 'Data Science'],
    difficulty: 'Hard',
    totalQuestions: 40,
    dateTaken: '2023-12-28',
  },
];

// Mock replacement questions pool
export const mockReplacementQuestions: MCQQuestion[] = [
  {
    id: 'rq-1',
    questionText: 'What is the difference between let and var in JavaScript?',
    options: { A: 'No difference', B: 'Scope and hoisting', C: 'Performance only', D: 'Syntax only' },
    correctAnswer: 'B',
    domain: 'JavaScript',
    topic: 'Variables & Data Types',
    difficulty: 'Medium',
  },
  {
    id: 'rq-2',
    questionText: 'Which method is used to convert a JSON string to an object?',
    options: { A: 'JSON.stringify()', B: 'JSON.parse()', C: 'JSON.toObject()', D: 'JSON.convert()' },
    correctAnswer: 'B',
    domain: 'JavaScript',
    topic: 'Variables & Data Types',
    difficulty: 'Easy',
  },
  {
    id: 'rq-3',
    questionText: 'What is the purpose of the useMemo hook in React?',
    options: { A: 'State management', B: 'Memoization of values', C: 'Side effects', D: 'Context creation' },
    correctAnswer: 'B',
    domain: 'React',
    topic: 'Hooks',
    difficulty: 'Medium',
  },
  {
    id: 'rq-4',
    questionText: 'Which hook should be used for subscribing to external data sources?',
    options: { A: 'useState', B: 'useEffect', C: 'useSyncExternalStore', D: 'useCallback' },
    correctAnswer: 'C',
    domain: 'React',
    topic: 'Hooks',
    difficulty: 'Hard',
  },
  {
    id: 'rq-5',
    questionText: 'What does the const keyword prevent in JavaScript?',
    options: { A: 'Value mutation', B: 'Reassignment', C: 'Property changes', D: 'All modifications' },
    correctAnswer: 'B',
    domain: 'JavaScript',
    topic: 'Variables & Data Types',
    difficulty: 'Medium',
  },
];

export const mockGeneratedSets: GeneratedQuestionSet[] = [
  {
    id: 'set-1',
    name: 'Assessment Set A',
    totalQuestions: 25,
    difficultyBreakdown: { easy: 8, medium: 12, hard: 5 },
    domainsCovered: ['JavaScript', 'React'],
    isPublished: false,
    version: 1,
    questions: [
      {
        id: 'q-1',
        questionText: 'What is the output of console.log(typeof null)?',
        options: { A: 'null', B: 'undefined', C: 'object', D: 'number' },
        correctAnswer: 'C',
        domain: 'JavaScript',
        topic: 'Variables & Data Types',
        difficulty: 'Medium',
      },
      {
        id: 'q-2',
        questionText: 'Which hook is used for side effects in React?',
        options: { A: 'useState', B: 'useEffect', C: 'useContext', D: 'useReducer' },
        correctAnswer: 'B',
        domain: 'React',
        topic: 'Hooks',
        difficulty: 'Easy',
      },
      {
        id: 'q-3',
        questionText: 'What does the spread operator (...) do in JavaScript?',
        options: { A: 'Adds numbers', B: 'Expands iterables', C: 'Creates loops', D: 'Defines functions' },
        correctAnswer: 'B',
        domain: 'JavaScript',
        topic: 'Variables & Data Types',
        difficulty: 'Easy',
      },
    ],
  },
  {
    id: 'set-2',
    name: 'Assessment Set B',
    totalQuestions: 25,
    difficultyBreakdown: { easy: 10, medium: 10, hard: 5 },
    domainsCovered: ['JavaScript', 'React'],
    isPublished: false,
    version: 1,
    questions: [
      {
        id: 'q-4',
        questionText: 'What is a closure in JavaScript?',
        options: { A: 'A way to close the browser', B: 'A function with access to parent scope', C: 'A type of loop', D: 'An error handler' },
        correctAnswer: 'B',
        domain: 'JavaScript',
        topic: 'Functions & Closures',
        difficulty: 'Medium',
      },
    ],
  },
  {
    id: 'set-3',
    name: 'Assessment Set C',
    totalQuestions: 25,
    difficultyBreakdown: { easy: 5, medium: 15, hard: 5 },
    domainsCovered: ['JavaScript', 'React'],
    isPublished: false,
    version: 1,
    questions: [],
  },
  {
    id: 'set-4',
    name: 'Assessment Set D',
    totalQuestions: 25,
    difficultyBreakdown: { easy: 7, medium: 11, hard: 7 },
    domainsCovered: ['JavaScript', 'React'],
    isPublished: false,
    version: 1,
    questions: [],
  },
  {
    id: 'set-5',
    name: 'Assessment Set E',
    totalQuestions: 25,
    difficultyBreakdown: { easy: 6, medium: 14, hard: 5 },
    domainsCovered: ['JavaScript', 'React'],
    isPublished: false,
    version: 1,
    questions: [],
  },
];
