import { BANDS, LEVELS, POOL_MULTIPLIER } from './constants';
import { Question } from './types';

export const bandCount = (pool: Question[], topic: string, band: string) =>
  pool.filter(
    (q) =>
      q.qtype === 'mcq' &&
      q.topic === topic &&
      q.difficulty === band &&
      !q.quarantined
  ).length;

export const cellTarget = (qPerForm: number, topicCount: number, band: string) => {
  const bi = BANDS.indexOf(band as any);
  const maxPct = Math.max(...LEVELS.map((l) => l.mix[bi])) / 100;
  const maxDraw = Math.ceil((qPerForm * maxPct) / Math.max(topicCount, 1));
  return Math.ceil(POOL_MULTIPLIER * maxDraw);
};

export const poolCapacity = (
  pool: Question[],
  poolTopics: string[],
  questionsPerForm: number
): number => {
  if (!pool.length || !poolTopics.length) return 0;
  const topicCount = poolTopics.length;
  const worst = Math.min(
    ...poolTopics.flatMap((topic) =>
      BANDS.map((b, bi) => {
        const maxPct = Math.max(...LEVELS.map((l) => l.mix[bi])) / 100;
        const maxDraw = Math.ceil((questionsPerForm * maxPct) / Math.max(topicCount, 1));
        const have = bandCount(pool, topic, b);
        return maxDraw > 0 ? Math.floor(have / maxDraw) : 99;
      })
    )
  );
  return Math.max(0, worst);
};

export const scoreTopicMatch = (topic: string, text: string): number => {
  const words = topic
    .toLowerCase()
    .split(/[\s&,]+/)
    .filter((w) => w.length > 2);
  const lower = text.toLowerCase();
  return words.reduce((s, w) => s + (lower.includes(w) ? 1 : 0), 0);
};

let qCounter = 1;

export function pickDemoQuestion(
  topic: string,
  band: string,
  usedTexts: string[]
): Question | null {
  const text = `Sample ${band} question for ${topic} #${qCounter++}`;
  if (usedTexts.includes(text)) return null;
  return {
    id: `q-${Date.now()}-${Math.random()}`,
    qtype: 'mcq',
    topic,
    difficulty: band,
    text,
    source: 'ai',
    options: ['Option A', 'Option B', 'Option C', 'Option D'],
    correctIndex: 0,
    explanation: 'Generated by AI.',
  };
}
